// ScrollAlignment.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class ScrollAlignment {
    private static final boolean IS_EXTENSIBLE = true;

    @IntDef({ScrollAlignment.NONE, ScrollAlignment.SCROLL_ALIGNMENT_CENTER, ScrollAlignment.SCROLL_ALIGNMENT_TOP, ScrollAlignment.SCROLL_ALIGNMENT_BOTTOM, ScrollAlignment.SCROLL_ALIGNMENT_LEFT, ScrollAlignment.SCROLL_ALIGNMENT_RIGHT, ScrollAlignment.SCROLL_ALIGNMENT_CLOSEST_EDGE})
    public @interface EnumType {
    }

    public static final int NONE = 0;
    public static final int SCROLL_ALIGNMENT_CENTER = 1;
    public static final int SCROLL_ALIGNMENT_TOP = 2;
    public static final int SCROLL_ALIGNMENT_BOTTOM = 3;
    public static final int SCROLL_ALIGNMENT_LEFT = 4;
    public static final int SCROLL_ALIGNMENT_RIGHT = 5;
    public static final int SCROLL_ALIGNMENT_CLOSEST_EDGE = 6;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 6;
    public static final int DEFAULT_VALUE = 0;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 6;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
        if (isKnownValue(value)) {
            return value;
        }
        return DEFAULT_VALUE;
    }

    private ScrollAlignment() {
    }
}