// LoadingMode.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/supports_loading_mode.mojom
//

package org.chromium.network.mojom;

import androidx.annotation.IntDef;

public final class LoadingMode {
    private static final boolean IS_EXTENSIBLE = false;

    @IntDef({LoadingMode.DEFAULT, LoadingMode.UNCREDENTIALED_PREFETCH, LoadingMode.UNCREDENTIALED_PRERENDER, LoadingMode.CREDENTIALED_PRERENDER, LoadingMode.FENCED_FRAME})
    public @interface EnumType {
    }

    public static final int DEFAULT = 0;
    public static final int UNCREDENTIALED_PREFETCH = 1;
    public static final int UNCREDENTIALED_PRERENDER = 2;
    public static final int CREDENTIALED_PRERENDER = 3;
    public static final int FENCED_FRAME = 4;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 4;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 4;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
        return value;
    }

    private LoadingMode() {
    }
}