// AuthenticatorStatus.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/webauthn/authenticator.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class AuthenticatorStatus {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        AuthenticatorStatus.SUCCESS,
        AuthenticatorStatus.PENDING_REQUEST,
        AuthenticatorStatus.NOT_ALLOWED_ERROR,
        AuthenticatorStatus.INVALID_DOMAIN,
        AuthenticatorStatus.CREDENTIAL_EXCLUDED,
        AuthenticatorStatus.NOT_IMPLEMENTED,
        AuthenticatorStatus.NOT_FOCUSED,
        AuthenticatorStatus.RESIDENT_CREDENTIALS_UNSUPPORTED,
        AuthenticatorStatus.USER_VERIFICATION_UNSUPPORTED,
        AuthenticatorStatus.ALGORITHM_UNSUPPORTED,
        AuthenticatorStatus.EMPTY_ALLOW_CREDENTIALS,
        AuthenticatorStatus.ANDROID_NOT_SUPPORTED_ERROR,
        AuthenticatorStatus.PROTECTION_POLICY_INCONSISTENT,
        AuthenticatorStatus.ABORT_ERROR,
        AuthenticatorStatus.OPAQUE_DOMAIN,
        AuthenticatorStatus.INVALID_PROTOCOL,
        AuthenticatorStatus.BAD_RELYING_PARTY_ID,
        AuthenticatorStatus.CANNOT_READ_AND_WRITE_LARGE_BLOB,
        AuthenticatorStatus.INVALID_ALLOW_CREDENTIALS_FOR_LARGE_BLOB,
        AuthenticatorStatus.FAILED_TO_SAVE_CREDENTIAL_ID_FOR_PAYMENT_EXTENSION,
        AuthenticatorStatus.REMOTE_DESKTOP_CLIENT_OVERRIDE_NOT_AUTHORIZED,
        AuthenticatorStatus.DEVICE_PUBLIC_KEY_ATTESTATION_REJECTED,
        AuthenticatorStatus.CERTIFICATE_ERROR,
        AuthenticatorStatus.ERROR_WITH_DOM_EXCEPTION_DETAILS,
        AuthenticatorStatus.UNKNOWN_ERROR})
    public @interface EnumType {}

    public static final int SUCCESS = 0;
    public static final int PENDING_REQUEST = 1;
    public static final int NOT_ALLOWED_ERROR = 2;
    public static final int INVALID_DOMAIN = 3;
    public static final int CREDENTIAL_EXCLUDED = 4;
    public static final int NOT_IMPLEMENTED = 5;
    public static final int NOT_FOCUSED = 6;
    public static final int RESIDENT_CREDENTIALS_UNSUPPORTED = 7;
    public static final int USER_VERIFICATION_UNSUPPORTED = 8;
    public static final int ALGORITHM_UNSUPPORTED = 9;
    public static final int EMPTY_ALLOW_CREDENTIALS = 10;
    public static final int ANDROID_NOT_SUPPORTED_ERROR = 11;
    public static final int PROTECTION_POLICY_INCONSISTENT = 12;
    public static final int ABORT_ERROR = 13;
    public static final int OPAQUE_DOMAIN = 14;
    public static final int INVALID_PROTOCOL = 15;
    public static final int BAD_RELYING_PARTY_ID = 16;
    public static final int CANNOT_READ_AND_WRITE_LARGE_BLOB = 17;
    public static final int INVALID_ALLOW_CREDENTIALS_FOR_LARGE_BLOB = 18;
    public static final int FAILED_TO_SAVE_CREDENTIAL_ID_FOR_PAYMENT_EXTENSION = 19;
    public static final int REMOTE_DESKTOP_CLIENT_OVERRIDE_NOT_AUTHORIZED = 20;
    public static final int DEVICE_PUBLIC_KEY_ATTESTATION_REJECTED = 21;
    public static final int CERTIFICATE_ERROR = 22;
    public static final int ERROR_WITH_DOM_EXCEPTION_DETAILS = 23;
    public static final int UNKNOWN_ERROR = 24;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 24;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 24;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private AuthenticatorStatus() {}
}