// DisplayMode.java is auto generated by mojom_bindings_generator.py, do not edit
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/manifest/display_mode.mojom
//
package org.chromium.blink.mojom

import androidx.annotation.IntDef
import org.chromium.mojo.bindings.DeserializationException

object DisplayMode {
    private const val IS_EXTENSIBLE = false
    const val UNDEFINED = 0
    const val BROWSER = 1
    const val MINIMAL_UI = 2
    const val STANDALONE = 3
    const val FULLSCREEN = 4
    const val WINDOW_CONTROLS_OVERLAY = 5
    const val MIN_VALUE = 0
    const val MAX_VALUE = 5
    @JvmStatic
    fun isKnownValue(value: Int): Boolean {
        return value >= 0 && value <= 5
    }

    fun validate(value: Int) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return
        throw DeserializationException("Invalid enum value.")
    }

    fun toKnownValue(value: Int): Int {
        return value
    }

    @IntDef(UNDEFINED, BROWSER, MINIMAL_UI, STANDALONE, FULLSCREEN, WINDOW_CONTROLS_OVERLAY)
    annotation class EnumType
}