// FederatedAuthUserInfoRequestResult.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/devtools/inspector_issue.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class FederatedAuthUserInfoRequestResult {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        FederatedAuthUserInfoRequestResult.SUCCESS,
        FederatedAuthUserInfoRequestResult.NOT_SAME_ORIGIN,
        FederatedAuthUserInfoRequestResult.NOT_IFRAME,
        FederatedAuthUserInfoRequestResult.NOT_POTENTIALLY_TRUSTWORTHY,
        FederatedAuthUserInfoRequestResult.NO_API_PERMISSION,
        FederatedAuthUserInfoRequestResult.NOT_SIGNED_IN_WITH_IDP,
        FederatedAuthUserInfoRequestResult.NO_ACCOUNT_SHARING_PERMISSION,
        FederatedAuthUserInfoRequestResult.INVALID_CONFIG_OR_WELL_KNOWN,
        FederatedAuthUserInfoRequestResult.INVALID_ACCOUNTS_RESPONSE,
        FederatedAuthUserInfoRequestResult.NO_RETURNING_USER_FROM_FETCHED_ACCOUNTS,
        FederatedAuthUserInfoRequestResult.UNHANDLED_REQUEST})
    public @interface EnumType {}

    public static final int SUCCESS = 0;
    public static final int NOT_SAME_ORIGIN = 1;
    public static final int NOT_IFRAME = 2;
    public static final int NOT_POTENTIALLY_TRUSTWORTHY = 3;
    public static final int NO_API_PERMISSION = 4;
    public static final int NOT_SIGNED_IN_WITH_IDP = 5;
    public static final int NO_ACCOUNT_SHARING_PERMISSION = 6;
    public static final int INVALID_CONFIG_OR_WELL_KNOWN = 7;
    public static final int INVALID_ACCOUNTS_RESPONSE = 8;
    public static final int NO_RETURNING_USER_FROM_FETCHED_ACCOUNTS = 9;
    public static final int UNHANDLED_REQUEST = 10;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 10;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 10;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private FederatedAuthUserInfoRequestResult() {}
}