// FileSystemAccessDirectoryHandle.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/file_system_access/file_system_access_directory_handle.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface FileSystemAccessDirectoryHandle extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends FileSystemAccessDirectoryHandle, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<FileSystemAccessDirectoryHandle, FileSystemAccessDirectoryHandle.Proxy> MANAGER = FileSystemAccessDirectoryHandle_Internal.MANAGER;

    void getPermissionStatus(
boolean writable, 
GetPermissionStatus_Response callback);

    interface GetPermissionStatus_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Integer> { }


    void requestPermission(
boolean writable, 
RequestPermission_Response callback);

    interface RequestPermission_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<FileSystemAccessError, Integer> { }


    void getFile(
String basename, boolean create, 
GetFile_Response callback);

    interface GetFile_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<FileSystemAccessError, FileSystemAccessFileHandle> { }


    void getDirectory(
String basename, boolean create, 
GetDirectory_Response callback);

    interface GetDirectory_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<FileSystemAccessError, FileSystemAccessDirectoryHandle> { }


    void getEntries(
FileSystemAccessDirectoryEntriesListener listener);


    void rename(
String newEntryName, 
Rename_Response callback);

    interface Rename_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<FileSystemAccessError> { }


    void move(
FileSystemAccessTransferToken destinationDirectory, String newEntryName, 
Move_Response callback);

    interface Move_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<FileSystemAccessError> { }


    void remove(
boolean recurse, 
Remove_Response callback);

    interface Remove_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<FileSystemAccessError> { }


    void removeEntry(
String basename, boolean recurse, 
RemoveEntry_Response callback);

    interface RemoveEntry_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<FileSystemAccessError> { }


    void resolve(
FileSystemAccessTransferToken possibleChild, 
Resolve_Response callback);

    interface Resolve_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<FileSystemAccessError, String[]> { }


    void transfer(
org.chromium.mojo.bindings.InterfaceRequest<FileSystemAccessTransferToken> token);


    void getUniqueId(

GetUniqueId_Response callback);

    interface GetUniqueId_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<FileSystemAccessError, String> { }


    void getCloudIdentifiers(

GetCloudIdentifiers_Response callback);

    interface GetCloudIdentifiers_Response extends org.chromium.mojo.bindings.Callbacks.Callback2<FileSystemAccessError, FileSystemAccessCloudIdentifier[]> { }


}
