// HidService.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/hid/hid.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface HidService extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends HidService, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<HidService, HidService.Proxy> MANAGER = HidService_Internal.MANAGER;

    void registerClient(
org.chromium.mojo.bindings.AssociatedInterfaceNotSupported client);


    void getDevices(

GetDevices_Response callback);

    interface GetDevices_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.device.mojom.HidDeviceInfo[]> { }


    void requestDevice(
HidDeviceFilter[] filters, HidDeviceFilter[] exclusionFilters, 
RequestDevice_Response callback);

    interface RequestDevice_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.device.mojom.HidDeviceInfo[]> { }


    void connect(
String deviceGuid, org.chromium.device.mojom.HidConnectionClient client, 
Connect_Response callback);

    interface Connect_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.device.mojom.HidConnection> { }


    void forget(
org.chromium.device.mojom.HidDeviceInfo deviceInfo, 
Forget_Response callback);

    interface Forget_Response extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


}
