// PopupWidgetHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/page/widget.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface PopupWidgetHost extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends PopupWidgetHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<PopupWidgetHost, PopupWidgetHost.Proxy> MANAGER = PopupWidgetHost_Internal.MANAGER;

    void requestClosePopup(
);


    void showPopup(
org.chromium.gfx.mojom.Rect initialRect, org.chromium.gfx.mojom.Rect anchorRect, 
ShowPopup_Response callback);

    interface ShowPopup_Response extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


    void setPopupBounds(
org.chromium.gfx.mojom.Rect bounds, 
SetPopupBounds_Response callback);

    interface SetPopupBounds_Response extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


}
