// RemoteObjectGateway.java is auto generated by mojom_bindings_generator.py, do not edit
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/remote_objects/remote_objects.mojom
//
package org.chromium.blink.mojom

import org.chromium.mojo.bindings.Interface

interface RemoteObjectGateway : Interface {
    interface Proxy : RemoteObjectGateway, Interface.Proxy

    fun addNamedObject(
        name: String?, objectId: Int
    )

    fun removeNamedObject(
        name: String?
    )

    companion object {
        @JvmField
        val MANAGER = RemoteObjectGateway_Internal.MANAGER
    }
}