// SmsStatus.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/sms/webotp_service.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class SmsStatus {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        SmsStatus.SUCCESS,
        SmsStatus.UNHANDLED_REQUEST,
        SmsStatus.CANCELLED,
        SmsStatus.ABORTED,
        SmsStatus.TIMEOUT,
        SmsStatus.BACKEND_NOT_AVAILABLE})
    public @interface EnumType {}

    public static final int SUCCESS = 0;
    public static final int UNHANDLED_REQUEST = 1;
    public static final int CANCELLED = 2;
    public static final int ABORTED = 3;
    public static final int TIMEOUT = 4;
    public static final int BACKEND_NOT_AVAILABLE = 5;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 5;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private SmsStatus() {}
}