// SpeculationHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/speculation_rules/speculation_rules.mojom
//

package org.chromium.blink.mojom;


public interface SpeculationHost extends org.chromium.mojo.bindings.Interface {



    interface Proxy extends SpeculationHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<SpeculationHost, SpeculationHost.Proxy> MANAGER = SpeculationHost_Internal.MANAGER;

    void updateSpeculationCandidates(
SpeculationCandidate[] candidates);


    void enableNoVarySearchSupport(
);


    void initiatePreview(
org.chromium.url.mojom.Url url);


}
