// WebDatabaseHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/webdatabase/web_database.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface WebDatabaseHost extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends WebDatabaseHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<WebDatabaseHost, WebDatabaseHost.Proxy> MANAGER = WebDatabaseHost_Internal.MANAGER;

    void openFile(
org.chromium.mojo_base.mojom.String16 vfsFileName, int desiredFlags, 
OpenFile_Response callback);

    interface OpenFile_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.mojo_base.mojom.File> { }


    void deleteFile(
org.chromium.mojo_base.mojom.String16 vfsFileName, boolean syncDir, 
DeleteFile_Response callback);

    interface DeleteFile_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Integer> { }


    void getFileAttributes(
org.chromium.mojo_base.mojom.String16 vfsFileName, 
GetFileAttributes_Response callback);

    interface GetFileAttributes_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Integer> { }


    void setFileSize(
org.chromium.mojo_base.mojom.String16 vfsFileName, long expectedSize, 
SetFileSize_Response callback);

    interface SetFileSize_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Boolean> { }


    void getSpaceAvailable(
org.chromium.url.internal.mojom.Origin origin, 
GetSpaceAvailable_Response callback);

    interface GetSpaceAvailable_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<Long> { }


    void opened(
org.chromium.url.internal.mojom.Origin origin, org.chromium.mojo_base.mojom.String16 databaseName, org.chromium.mojo_base.mojom.String16 databaseDescription);


    void modified(
org.chromium.url.internal.mojom.Origin origin, org.chromium.mojo_base.mojom.String16 databaseName);


    void closed(
org.chromium.url.internal.mojom.Origin origin, org.chromium.mojo_base.mojom.String16 databaseName);


    void handleSqliteError(
org.chromium.url.internal.mojom.Origin origin, org.chromium.mojo_base.mojom.String16 databaseName, int error);


}
