// WebUsbService.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/usb/web_usb_service.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface WebUsbService extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends WebUsbService, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<WebUsbService, WebUsbService.Proxy> MANAGER = WebUsbService_Internal.MANAGER;

    void getDevices(

GetDevices_Response callback);

    interface GetDevices_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.device.mojom.UsbDeviceInfo[]> { }


    void getDevice(
String guid, org.chromium.mojo.bindings.InterfaceRequest<org.chromium.device.mojom.UsbDevice> deviceReceiver);


    void getPermission(
WebUsbRequestDeviceOptions options, 
GetPermission_Response callback);

    interface GetPermission_Response extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.device.mojom.UsbDeviceInfo> { }


    void forgetDevice(
String guid, 
ForgetDevice_Response callback);

    interface ForgetDevice_Response extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


    void setClient(
org.chromium.mojo.bindings.AssociatedInterfaceNotSupported client);


}
