// WorkletDevToolsHost.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/worker/worklet_global_scope_creation_params.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;


public interface WorkletDevToolsHost extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends WorkletDevToolsHost, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<WorkletDevToolsHost, WorkletDevToolsHost.Proxy> MANAGER = WorkletDevToolsHost_Internal.MANAGER;

    void onReadyForInspection(
DevToolsAgent agent, org.chromium.mojo.bindings.InterfaceRequest<DevToolsAgentHost> agentHost);


}
