// PressureClient.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/device/public/mojom/pressure_manager.mojom
//

package org.chromium.device.mojom;

public interface PressureClient extends org.chromium.mojo.bindings.Interface {


    interface Proxy extends PressureClient, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<PressureClient, PressureClient.Proxy> MANAGER = PressureClient_Internal.MANAGER;

    void onPressureUpdated(PressureUpdate update);


}
