// SmartCardCreateContextResult.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/device/public/mojom/smart_card.mojom
//

package org.chromium.device.mojom;

public final class SmartCardCreateContextResult extends org.chromium.mojo.bindings.Union {

    public static final class Tag {
        public static final int Context = 0;
        public static final int Error = 1;
    }

    private SmartCardContext mContext;
    private int mError;

    public void setContext(SmartCardContext context) {
        this.mTag = Tag.Context;
        this.mContext = context;
    }

    public SmartCardContext getContext() {
        assert this.mTag == Tag.Context;
        return this.mContext;
    }

    public void setError(int error) {
        this.mTag = Tag.Error;
        this.mError = error;
    }

    public int getError() {
        assert this.mTag == Tag.Error;
        return this.mError;
    }


    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder0, int offset) {
        encoder0.encode(org.chromium.mojo.bindings.BindingsHelper.UNION_SIZE, offset);
        encoder0.encode(this.mTag, offset + 4);
        switch (mTag) {
            case Tag.Context: {

                encoder0.encode(this.mContext, offset + 8, false, SmartCardContext.MANAGER);
                break;
            }
            case Tag.Error: {

                encoder0.encode(this.mError, offset + 8);
                break;
            }
            default: {
                break;
            }
        }
    }

    public static SmartCardCreateContextResult deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message).decoderForSerializedUnion(), 0);
    }

    public static final SmartCardCreateContextResult decode(org.chromium.mojo.bindings.Decoder decoder0, int offset) {
        org.chromium.mojo.bindings.DataHeader dataHeader = decoder0.readDataHeaderForUnion(offset);
        if (dataHeader.size == 0) {
            return null;
        }
        SmartCardCreateContextResult result = new SmartCardCreateContextResult();
        switch (dataHeader.elementsOrVersion) {
            case Tag.Context: {

                result.mContext = decoder0.readServiceInterface(offset + org.chromium.mojo.bindings.DataHeader.HEADER_SIZE, false, SmartCardContext.MANAGER);
                result.mTag = Tag.Context;
                break;
            }
            case Tag.Error: {

                result.mError = decoder0.readInt(offset + org.chromium.mojo.bindings.DataHeader.HEADER_SIZE);
                SmartCardError.validate(result.mError);
                result.mError = SmartCardError.toKnownValue(result.mError);
                result.mTag = Tag.Error;
                break;
            }
            default: {
                break;
            }
        }
        return result;
    }
}