// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../net/socket/socket_tag.cc
package org.chromium.net

import androidx.annotation.IntDef

@IntDef(TrafficStatsUid.UNSET)
@Retention(AnnotationRetention.SOURCE)
annotation class TrafficStatsUid {
    companion object {
        const val UNSET = -1
    }
}