// CompositorFrameSinkClient.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/viz/public/mojom/compositing/compositor_frame_sink.mojom
//

package org.chromium.viz.mojom;

import androidx.annotation.IntDef;


public interface CompositorFrameSinkClient extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends CompositorFrameSinkClient, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<CompositorFrameSinkClient, CompositorFrameSinkClient.Proxy> MANAGER = CompositorFrameSinkClient_Internal.MANAGER;

    void didReceiveCompositorFrameAck(
ReturnedResource[] resources);


    void onBeginFrame(
BeginFrameArgs args, java.util.Map<Integer, FrameTimingDetails> details, boolean frameAck, ReturnedResource[] resources);


    void onBeginFramePausedChanged(
boolean paused);


    void reclaimResources(
ReturnedResource[] resources);


    void onCompositorFrameTransitionDirectiveProcessed(
int sequenceId);


}
