// FilterType.java is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/viz/public/mojom/compositing/filter_operation.mojom

package org.chromium.viz.mojom;

import androidx.annotation.IntDef;

public final class FilterType {
    private static final boolean IS_EXTENSIBLE = true;

    @IntDef({FilterType.GRAYSCALE, FilterType.SEPIA, FilterType.SATURATE, FilterType.HUE_ROTATE, FilterType.INVERT, FilterType.BRIGHTNESS, FilterType.CONTRAST, FilterType.OPACITY, FilterType.BLUR, FilterType.DROP_SHADOW, FilterType.COLOR_MATRIX, FilterType.ZOOM, FilterType.REFERENCE, FilterType.SATURATING_BRIGHTNESS, FilterType.ALPHA_THRESHOLD, FilterType.OFFSET, FilterType.NEW_FILTER_TYPE})
    public @interface EnumType {
    }

    public static final int GRAYSCALE = 0;
    public static final int SEPIA = 1;
    public static final int SATURATE = 2;
    public static final int HUE_ROTATE = 3;
    public static final int INVERT = 4;
    public static final int BRIGHTNESS = 5;
    public static final int CONTRAST = 6;
    public static final int OPACITY = 7;
    public static final int BLUR = 8;
    public static final int DROP_SHADOW = 9;
    public static final int COLOR_MATRIX = 10;
    public static final int ZOOM = 11;
    public static final int REFERENCE = 12;
    public static final int SATURATING_BRIGHTNESS = 13;
    public static final int ALPHA_THRESHOLD = 14;
    public static final int OFFSET = 15;
    public static final int NEW_FILTER_TYPE = 16;
    public static final int MIN_VALUE = 1;
    public static final int MAX_VALUE = 16;

    public static boolean isKnownValue(int value) {
        return value >= 1 && value <= 16;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
        return value;
    }

    private FilterType() {
    }
}
