//
// This file was generated by third_party/jni_zero/jni_generator.py
//
package org.chromium.components.download;

import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniStaticTestMocker;
import org.jni_zero.NativeLibraryLoadedStatus;

@CheckDiscard("crbug.com/993421")
class DownloadCollectionBridgeJni implements DownloadCollectionBridge.Natives {
    private static DownloadCollectionBridge.Natives testInstance;

    public static final JniStaticTestMocker<DownloadCollectionBridge.Natives> TEST_HOOKS = new JniStaticTestMocker<DownloadCollectionBridge.Natives>() {
        @Override
        public void setInstanceForTesting(DownloadCollectionBridge.Natives instance) {
            if (!GEN_JNI.TESTING_ENABLED) {
                throw new RuntimeException("Tried to set a JNI mock when mocks aren't enabled!");
            }
            testInstance = instance;
        }
    };

    @Override
    public int getExpirationDurationInDays() {
        return (int) GEN_JNI.org_chromium_components_download_DownloadCollectionBridge_getExpirationDurationInDays();
    }

    public static DownloadCollectionBridge.Natives get() {
        if (GEN_JNI.TESTING_ENABLED) {
            if (testInstance != null) {
                return testInstance;
            }
            if (GEN_JNI.REQUIRE_MOCK) {
                throw new UnsupportedOperationException("No mock found for the native implementation of DownloadCollectionBridge.Natives. " + "The current configuration requires implementations be mocked.");
            }
        }
        NativeLibraryLoadedStatus.checkLoaded();
        return new DownloadCollectionBridgeJni();
    }
}
