// Origin.java is auto generated by mojom_bindings_generator.py, do not edit
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     url/mojom/origin.mojom
//
package org.chromium.url.internal.mojom

import org.chromium.mojo.bindings.DataHeader
import org.chromium.mojo.bindings.Decoder
import org.chromium.mojo.bindings.Encoder
import org.chromium.mojo.bindings.Message
import org.chromium.mojo.bindings.Struct
import org.chromium.mojo_base.mojom.UnguessableToken
import java.nio.ByteBuffer

class Origin private constructor(version: Int) : Struct(STRUCT_SIZE, version) {
    var scheme: String? = null
    var host: String? = null
    var port: Short = 0
    var nonceIfOpaque: UnguessableToken? = null

    constructor() : this(0)

    override fun encode(encoder: Encoder) {
        val encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO)
        encoder0.encode(scheme, 8, false)
        encoder0.encode(host, 16, false)
        encoder0.encode(port, 24)
        encoder0.encode(nonceIfOpaque, 32, true)
    }

    companion object {
        private const val STRUCT_SIZE = 40
        private val VERSION_ARRAY = arrayOf(DataHeader(40, 0))
        private val DEFAULT_STRUCT_INFO = VERSION_ARRAY[0]

        fun deserialize(message: Message?): Origin? {
            return decode(Decoder(message))
        }

        /**
         * Similar to the method above, but deserializes from a |ByteBuffer| instance.
         *
         * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
         */
        fun deserialize(data: ByteBuffer?): Origin? {
            return deserialize(
                Message(
                    data, ArrayList()
                )
            )
        }

        @JvmStatic
        fun decode(decoder0: Decoder?): Origin? {
            if (decoder0 == null) {
                return null
            }
            decoder0.increaseStackDepth()
            val result: Origin
            try {
                val mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY)
                val elementsOrVersion = mainDataHeader.elementsOrVersion
                result = Origin(elementsOrVersion)
                run { result.scheme = decoder0.readString(8, false) }
                run { result.host = decoder0.readString(16, false) }
                run { result.port = decoder0.readShort(24) }
                run {
                    val decoder1 = decoder0.readPointer(32, true)
                    result.nonceIfOpaque = UnguessableToken.decode(decoder1)
                }
            } finally {
                decoder0.decreaseStackDepth()
            }
            return result
        }
    }
}