// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../base/android/child_process_binding_types.h
package org.chromium.base

import androidx.annotation.IntDef
import org.chromium.base.ChildBindingState

@IntDef(
    ChildBindingState.UNBOUND,
    ChildBindingState.WAIVED,
    ChildBindingState.MODERATE,
    ChildBindingState.STRONG,
    ChildBindingState.MAX_VALUE
)
@Retention(
    AnnotationRetention.SOURCE
)
annotation class ChildBindingState {
    companion object {
        const val UNBOUND = 0
        const val WAIVED = 1
        const val MODERATE = 2
        const val STRONG = 3
        const val MAX_VALUE = 3
    }
}